development:
  adapter: postgresql
  encoding: unicode
  database: Barebones
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: Barebones_test
  pool: 5
  username: Barebones
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Barebones_production
  pool: 5
  username: Barebones
  password:
